version: '2'
services:
   node-red:
    container_name: mynodered
    image: nodered/node-red:3.0.2-18
    ports:
      - "1880:1880"
    volumes:
      - ./nodered-data:/data
    restart: unless-stopped